"""Generate a shareable markdown 'case file' from a captured Loupe trace.

Used by `loupe report <trace-id>`. Output is designed to be pasted into a
Twitter/X thread, an issue, or a blog post.
"""

from __future__ import annotations

import datetime as dt
import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

from loupe.annotation import AnnotationStore


def render_trace_markdown(trace_path: Path) -> str:
    header, steps = _read_trace(trace_path)
    annotations = AnnotationStore().load(header["trace_id"])
    ann_by_step = {a.step_id: a for a in annotations}

    started = _fmt_ts(header.get("started_at"))
    duration_ms = _duration_ms(header.get("started_at"), header.get("ended_at"))
    failed = bool(header.get("metadata", {}).get("failed"))
    status_badge = "❗ failed" if failed else "✓ ok"

    lines: list[str] = []
    lines.append(f"# Case File · {header['name']}")
    lines.append("")
    lines.append(
        f"> `{header['trace_id'][:12]}` · "
        f"{header.get('framework') or 'untagged'} · "
        f"{started} · "
        f"{duration_ms:.0f} ms · "
        f"**{status_badge}**"
    )
    lines.append("")

    if failed and header.get("metadata", {}).get("error"):
        lines.append("## Top-level error")
        lines.append("```")
        lines.append(str(header["metadata"]["error"]))
        lines.append("```")
        lines.append("")

    if annotations:
        lines.append("## Annotations")
        for ann in annotations:
            lines.append("")
            lines.append(f"### {ann.failure_category} · {ann.severity}")
            if ann.notes:
                lines.append("")
                lines.append(ann.notes)
            if ann.mitigation:
                lines.append("")
                lines.append(f"**Mitigation:** {ann.mitigation}")
            if ann.tags:
                lines.append("")
                lines.append(f"**Tags:** {', '.join(ann.tags)}")
            if ann.annotator:
                lines.append("")
                lines.append(f"*— annotated by {ann.annotator}*")
        lines.append("")

    lines.append("## Steps")
    lines.append("")
    lines.append("| # | kind | name | duration | status |")
    lines.append("|---|------|------|---------:|--------|")
    for i, s in enumerate(steps, 1):
        dur = _duration_ms(s.get("started_at"), s.get("ended_at"))
        tag = " ◉" if s.get("step_id") in ann_by_step else ""
        status = "**failed**" if s.get("error") else "ok"
        lines.append(
            f"| {i} | `{s['kind']}` | {s['name']}{tag} | {dur:.1f} ms | {status} |"
        )
    lines.append("")

    failures = [s for s in steps if s.get("error")]
    if failures:
        lines.append("## Failure detail")
        for s in failures:
            lines.append("")
            lines.append(f"### Step `{s['name']}` ({s['kind']})")
            lines.append("```")
            lines.append(s["error"])
            lines.append("```")
            if s.get("inputs"):
                lines.append("")
                lines.append("**Inputs**")
                lines.append("```json")
                lines.append(json.dumps(s["inputs"], indent=2))
                lines.append("```")
            if s.get("outputs"):
                lines.append("")
                lines.append("**Outputs**")
                lines.append("```json")
                lines.append(json.dumps(s["outputs"], indent=2))
                lines.append("```")
            tagged = ann_by_step.get(s.get("step_id", ""))
            if tagged is not None:
                lines.append("")
                lines.append("**Annotation**")
                lines.append("```json")
                lines.append(json.dumps(asdict(tagged), indent=2))
                lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by [Loupe](https://loupe.dev) — open-source forensics for AI agents.*")
    return "\n".join(lines)


def _read_trace(path: Path) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    header: dict[str, Any] = {}
    steps: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            obj = json.loads(line)
            kind = obj.pop("_type", None)
            if kind == "trace":
                header = obj
            elif kind == "step":
                steps.append(obj)
    return header, steps


def _fmt_ts(ts: float | None) -> str:
    if ts is None:
        return "—"
    return dt.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")


def _duration_ms(start: float | None, end: float | None) -> float:
    if start is None or end is None:
        return 0.0
    return max(0.0, (end - start) * 1000)
