"""Tests for loupe.report_html and `loupe report --html`."""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from loupe import record_step, trace
from loupe.annotation import Annotation, AnnotationStore
from loupe.cli import app
from loupe.report_html import render_trace_html
from loupe.store import JSONLStore


@pytest.fixture()
def loupe_home(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    home = tmp_path / "loupe-home"
    home.mkdir()
    monkeypatch.setenv("LOUPE_HOME", str(home))
    monkeypatch.setenv("COLUMNS", "200")
    from loupe import store as store_mod

    store_mod._default = None
    return home


def _make_failing_trace(home: Path) -> tuple[str, str]:
    store = JSONLStore(root=home / "traces")
    captured: dict[str, str] = {}

    @trace(name="html-test-agent", framework="test", store=store)
    def agent() -> None:
        record_step("thought", "plan")
        s = record_step("error", "boom", error="kaboom")
        assert s
        captured["step"] = s.step_id
        raise RuntimeError("boom")

    with pytest.raises(RuntimeError):
        agent()

    trace_id = next(iter(p.stem for p in (home / "traces").glob("*.jsonl")))
    return trace_id, captured["step"]


def test_render_trace_html_produces_self_contained_document(loupe_home: Path) -> None:
    trace_id, _ = _make_failing_trace(loupe_home)
    path = next((loupe_home / "traces").glob("*.jsonl"))
    html = render_trace_html(path)

    assert html.startswith("<!DOCTYPE html>"), "must be a complete HTML doc"
    assert "</html>" in html
    assert "html-test-agent" in html
    assert "Generated by" in html
    assert "loupe.dev" in html
    # No external CDN includes that would break offline viewing
    assert "https://fonts.googleapis.com" not in html
    assert "src=\"http" not in html
    assert "link rel=\"stylesheet\" href=\"http" not in html
    # The trace data is inlined
    assert trace_id in html


def test_render_trace_html_includes_annotation_card(loupe_home: Path) -> None:
    trace_id, step_id = _make_failing_trace(loupe_home)
    AnnotationStore().add(Annotation(
        trace_id=trace_id, step_id=step_id,
        failure_category="off-task",
        notes="test annotation note",
        mitigation="test mitigation note",
        severity="high",
    ))
    path = next((loupe_home / "traces").glob("*.jsonl"))
    html = render_trace_html(path)
    assert "off-task" in html
    assert "test annotation note" in html
    assert "test mitigation note" in html


def test_cli_report_html_flag(loupe_home: Path, tmp_path: Path) -> None:
    trace_id, _ = _make_failing_trace(loupe_home)
    out = tmp_path / "case.html"
    result = CliRunner().invoke(app, ["report", trace_id[:12], "--html", "--out", str(out)])
    assert result.exit_code == 0
    text = out.read_text(encoding="utf-8")
    assert text.startswith("<!DOCTYPE html>")
    assert "html-test-agent" in text
